language: julia
sudo: false
dist: trusty
os:
  - linux
julia:
  - 1.5
notifications:
  email: false

codecov: true

script:
  - julia --project --color=yes --check-bounds=yes -e 'using Pkg; 
                                                      Pkg.instantiate(); 
                                                      Pkg.build();
                                                      Pkg.test();'

  - sudo apt-get update
  - sudo apt-get -qq install libxt6 libxrender1 libxext6 libgl1-mesa-glx libqt5widgets5 xvfb
  - export DOCUMENTER_DEBUG="true"
  - julia --project=docs/ --color=yes -e 'using Pkg;
                                          Pkg.develop(PackageSpec(path=pwd())); 
                                          Pkg.instantiate(); 
                                          Pkg.build("MixedLayerModel")'
  - julia --project=docs/ --color=yes 'docs/make.jl'
